// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package override

import (
	"github.com/michaelzx/sqlc-stand-alone-queries-struct-testdata/pkg"
)

type Foo struct {
	Other   string
	Total   int64
	Retyped pkg.CustomType
}
